#! /bin/bash

set -e

if [[ $( command -v python3 ) ]]; then
    python_program=$( which python3 )
elif [[ $( command -v python ) ]]; then
    python_program=$( which python )
else
    echo "ERROR: Unable to run './spotify-genie'. Could not find Python installation on machine."
    exit 1
fi

if [[ "$#" -eq 0 ]]; then
    $python_program main.py --help
else
    $python_program main.py "$@"
fi
